### ISSUE TITLE
attempts to fix some build issues

### ISSUE THREAD

**Issue by dbrooke** [adamgreig/ukhasnet-influxdb#1]
The build initially failed with an error in one of the libraries so I tried an update:

cargo update
    Updating crates.io index
error: failed to select a version for the requirement `security-framework = "^0.1.9"`
candidate versions found which didn't match: 2.7.0, 2.6.1, 2.6.0, ...
location searched: crates.io index
required by package `native-tls v0.1.0`
    ... which satisfies dependency `native-tls = "^0.1"` of package `hyper-native-tls v0.2.0`
    ... which satisfies dependency `hyper-native-tls = "^0.2"` of package `reqwest v0.4.0`
    ... which satisfies dependency `reqwest = "^0.4"` of package `ukhasnet-influxdb v0.2.2 (/home/db/git/ukhasnet-influxdb)`

I found that the oldest version of reqwest which would update was 0.9 so continued with that version

I attempted to fix the remaining errors but I'm not familiar with Rust and don't know how to proceed with the error[E0521]: borrowed data escapes outside of function

I pushed my work in progress to https://github.com/dbrooke/ukhasnet-influxdb/commit/9fc018f41279dd9c24c424cecd36e73af8c8c035

**Comment by adamgreig** [comment]
Thanks, looks like you almost got it! I think the final issue was cloning the body to be submitted, as for some reason it now borrows it for longer than before: `.body(line.to_owned())`. I've pushed a commit does that and updates to reqwest 0.11, and seems to let it build OK now.

**Comment by dbrooke** [comment]
Thanks. It seems to be working now, I just need to sort out my influxdb permissions to accept the posts.
